/// A reference type that serves as the single source of truth for a slice of
/// application state.
///
/// Conforming types hold observable properties that drive the UI and are
/// modified exclusively through `Action` and `AsyncAction` dispatches. The
/// `@Store` macro can synthesize the conformance automatically, generating
/// the `Proxy` type and a set of mutator actions for every stored property.
///
/// ```swift
/// @Store @Observable
/// final class ToDoStore {
///     var title: String = ""
///     var todos: [ToDo] = []
/// }
/// ```
///
/// Actions are dispatched through the convenience methods provided by the
/// default extension, either by value or by key path:
///
/// ```swift
/// store.dispatch(interactor.toggleAction)
/// store.dispatch(\.toggleAction)
/// await store.dispatch(interactor.fetchAction)
/// ```
public protocol Store: AnyObject {
    /// An immutable snapshot of the store's state, used by ``Middleware`` and
    /// ``AsyncMiddleware`` to read values without risking mutation during
    /// asynchronous work.
    associatedtype Proxy

    /// Returns the current proxy snapshot of this store.
    var proxy: Self.Proxy { get }

    /// The mediator of reducers and middlwares owners (business-rulers)
    associatedtype I: Interactor

    /// Returns the associated Interactor
    var interactor: Self.I { get }
}

public extension Store {
    /// Dispatches a synchronous action against this store.
    ///
    /// Each component inside the action (reducers, middlewares, late reducers)
    /// runs sequentially in declaration order.
    ///
    /// - Parameters:
    ///   - action: The ``Action`` to dispatch.
    ///   - args: The variadic arguments forwarded to the action's builder closure.
    func dispatch<each Argument>(
        _ action: Action<Self, repeat each Argument>,
        _ args: repeat each Argument
    ) {
        action.dispatch(self, repeat each args)
    }

    /// Dispatches a synchronous action located at the given key path.
    ///
    /// This overload lets you dispatch without holding a direct reference to
    /// the action value — handy when the action is a stored property of the
    /// store itself (e.g. a mutator generated by the `@Store` macro).
    ///
    /// - Parameters:
    ///   - actionPath: A key path from this store to the ``Action``.
    ///   - args: The variadic arguments forwarded to the action's builder closure.
    func dispatch<each Argument>(
        _ actionPath: KeyPath<Self, Action<Self, repeat each Argument>>,
        _ args: repeat each Argument
    ) {
        self[keyPath: actionPath].dispatch(self, repeat each args)
    }

    /// Dispatches a synchronous action located at the store's interactor
    ///
    /// - Parameters:
    ///   - actionPath: A key path from this store's interactor to the ``Action``.
    ///   - args: The variadic arguments forwarded to the action's builder closure.
    func dispatch<each Argument>(
        _ actionPath: KeyPath<Self.I, Action<Self, repeat each Argument>>,
        _ args: repeat each Argument
    ) {
        self.interactor[keyPath: actionPath].dispatch(self, repeat each args)
    }

    /// Dispatches an asynchronous action against this store.
    ///
    /// Components run sequentially with `await`, so each middleware can
    /// perform asynchronous work (network calls, delays, etc.) before the
    /// next component in the pipeline executes.
    ///
    /// - Parameters:
    ///   - asyncAction: The ``AsyncAction`` to dispatch.
    ///   - args: The variadic arguments forwarded to the action's builder closure.
    func dispatch<each Argument>(
        _ asyncAction: AsyncAction<Self, repeat each Argument>,
        _ args: repeat each Argument
    ) async {
        await asyncAction.dispatch(self, repeat each args)
    }

    /// Dispatches an asynchronous action located at the given key path.
    ///
    /// - Parameters:
    ///   - asyncActionPath: A key path from this store to the ``AsyncAction``.
    ///   - args: The variadic arguments forwarded to the action's builder closure.
    func dispatch<each Argument>(
        _ asyncActionPath: KeyPath<Self, AsyncAction<Self, repeat each Argument>>,
        _ args: repeat each Argument
    ) async {
        await self[keyPath: asyncActionPath].dispatch(self, repeat each args)
    }

    /// Dispatches an asynchronous action located at the store's interactor
    ///
    /// - Parameters:
    ///   - asyncActionPath: A key path from this store to the ``AsyncAction``.
    ///   - args: The variadic arguments forwarded to the action's builder closure.
    func dispatch<each Argument>(
        _ asyncActionPath: KeyPath<Self.I, AsyncAction<Self, repeat each Argument>>,
        _ args: repeat each Argument
    ) async {
        await self.interactor[keyPath: asyncActionPath].dispatch(self, repeat each args)
    }
}
